version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app_${APP_NAME}
    command: >
      sh -c
         'mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache storage/logs bootstrap/cache \
          && chmod -R 777 storage bootstrap/cache storage \
          && composer update -o --no-interaction \
          && composer dump-autoload -o \
          && php artisan optimize \
          && php artisan event:cache \
          && php artisan config:cache \
          && php artisan route:cache \
          && php artisan view:cache \
          && vendor/bin/pint \
          && npm update \
          && rm -rf public/build \
          && rm -rf public/hot \
          && npm run build \
          && php artisan octane:start --server=swoole --host=0.0.0.0 --port=9000 --watch'
    ports:
      - "${APP_PORT}:9000"
    volumes:
      - ./app/:/var/www/html/
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini